import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ErrorBoundary } from "react-error-boundary";

import '@/styles/global.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


function GeneralError() {
  return (
    <div role="alert">
      <p>Something went wrong:</p>
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <ErrorBoundary fallback={<GeneralError />}>
          {children}
        </ErrorBoundary>
      </body>
    </html>
  )
}
