import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextIntlClientProvider, useLocale, useTranslations } from 'next-intl';
import { ErrorBoundary } from "react-error-boundary";

import '@/styles/global.css'
import { notFound } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


function GeneralError() {
  const t = useTranslations('error')

  return (
    <div role="alert">
      <p>{t('general')}</p>
    </div>
  );
}

type RootLayoutProps = {
  children: React.ReactNode,
  params: { locale: string }
}

export default async function RootLayout({
  children,
  params: { locale }
}: RootLayoutProps) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`${inter.className} dark`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ErrorBoundary fallback={<GeneralError />}>
            {children}
          </ErrorBoundary>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
